<?php

namespace App\Models;


use App\Traits\HistoryTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends BaseModel
{
    use HistoryTrait;
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($item) {
            $item->subcategories()->each(function ($subcat) {
                $subcat->delete();
            });
        });
    }

    public function subcategories()
    {
        return $this->hasMany(Subcategory::class);
    }
}
