<?php

namespace App\Models;

use App\Traits\HistoryTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CheckInItem extends Model
{
    use HistoryTrait;
    use HasFactory;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($item) {
            $product = Product::query()->findOrFail($item->product_id);
            $product->increment('quantity', $item->quantity);
        });
        static::updating(function ($item) {
            $product = Product::query()->findOrFail($item->product_id);
            $product->quantity = $product->quantity - $item->getOriginal('quantity') + $item->quantity;
            $product->saveOrFail();
        });
        static::deleting(function ($item) {
            $product = Product::query()->findOrFail($item->product_id);
            $product->decrement('quantity', $item->quantity);
        });
    }

    public function checkIn()
    {
        return $this->belongsTo(CheckIn::class, 'check_in_id', 'id');
    }
}
