<?php

namespace App\Models;


use App\Traits\HistoryTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class PurchasePayment extends BaseModel
{
    use HasFactory, HistoryTrait;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (self $purchasePayment) {
            $purchasePayment->given_by = auth()->id();
            $purchasePayment->payment_amount = round($purchasePayment->payment_amount, 2);
        });
        static::updating(function (self $purchasePayment) {
            $purchasePayment->payment_amount = round($purchasePayment->payment_amount, 2);
        });
    }

    public function purchase()
    {
        return $this->belongsTo(Purchase::class, 'purchase_id', 'id');
    }

    public function supplier()
    {
        return $this->hasOne(Supplier::class, 'id', 'supplier_id');
    }
}
